# Generated by Django 5.0.11 on 2025-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loi_nhan', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
