# Generated by Django 5.0.11 on 2025-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lienhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten_phu_huynh', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('truong_thcs', models.CharField(max_length=255)),
                ('nam_sinh', models.IntegerField()),
                ('tinh_thanh_pho', models.CharField(max_length=100)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
