# Generated by Django 5.0.11 on 2025-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_dangky_ho_ten_phu_huynh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangky',
            old_name='birth_year',
            new_name='nam_sinh',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='school',
        ),
        migrations.AddField(
            model_name='dangky',
            name='so_dien_thoai',
            field=models.CharField(default='Nhập số điện thoại', max_length=20),
        ),
        migrations.AddField(
            model_name='dangky',
            name='ten_phu_huynh',
            field=models.CharField(default='Nhập tên phụ huynh', max_length=255),
        ),
        migrations.AddField(
            model_name='dangky',
            name='tinh_thanh',
            field=models.CharField(default='Nhập tỉnh/thành phố', max_length=50),
        ),
        migrations.AddField(
            model_name='dangky',
            name='truong',
            field=models.CharField(default='Nhập tên trường', max_length=255),
        ),
        migrations.AlterField(
            model_name='dangky',
            name='email',
            field=models.EmailField(default='Nhập email', max_length=254),
        ),
    ]
