# Generated by Django 5.0.11 on 2025-02-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dangky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangky',
            name='ho_ten_phu_huynh',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='nam_sinh',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='ngay_dang_ky',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='so_dien_thoai',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='tinh_thanh_pho',
        ),
        migrations.RemoveField(
            model_name='dangky',
            name='truong_thcs',
        ),
        migrations.AddField(
            model_name='dangky',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='dangky',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='dangky',
            name='parent_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='dangky',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='dangky',
            name='school',
            field=models.CharField(default='Unknown School', max_length=100),
        ),
        migrations.AlterField(
            model_name='dangky',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
