# Generated by Django 4.1.13 on 2025-02-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DangKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phu_huynh', models.CharField(default='Nhập tên phụ huynh', max_length=255)),
                ('email', models.EmailField(default='Nhập email', max_length=254)),
                ('so_dien_thoai', models.CharField(default='Nhập số điện thoại', max_length=20)),
                ('truong', models.CharField(default='Nhập tên trường', max_length=255)),
                ('nam_sinh', models.IntegerField(default=2000)),
                ('tinh_thanh', models.CharField(default='Nhập tỉnh/thành phố', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loi_nhan', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('nam_hoc', models.CharField(max_length=10)),
                ('nam_sinh', models.DateField()),
                ('dia_chi_thuong_tru', models.CharField(max_length=255)),
                ('que_quan', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('thong_tin_gia_dinh', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('mssv', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nam_hoc', models.CharField(blank=True, max_length=10, null=True)),
                ('nam_sinh', models.CharField(blank=True, max_length=4, null=True)),
                ('dia_chi_thuong_tru', models.TextField(blank=True, null=True)),
                ('que_quan', models.TextField(blank=True, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('thong_tin_gia_dinh', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
