# Generated by Django 5.0.11 on 2025-02-04 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('nam_hoc', models.CharField(max_length=10)),
                ('nam_sinh', models.DateField()),
                ('dia_chi_thuong_tru', models.CharField(max_length=255)),
                ('que_quan', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('thong_tin_gia_dinh', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
